import collections
from binascii import hexlify

# Ciphertext of Flag
c0 = "7bdefb92aa75228b995ef32f7baa9cc082ffb70fcd92c883e97ddda70f7b05a9"

# Fabricated Plaintext
pa = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# ciphertext of "pa" generated by the same key as "c0"
ca = "288fa3c5fa2674dbc907a17a29fccd91daade55c9bc099dab02f89f25d2952fb"

def xorHexString(a, b):
    res = int(a, 16) ^ int(b, 16)
    return hex(res)

def stringToHex(a):
    h = hexlify(a.encode())
    return h.decode()

something = str(xorHexString(stringToHex(pb), cb))[2:]
flagHex = xorHexString(something, c0)
flagBytes = bytes.fromhex(flagHex[2:])
flag = flagBytes.decode("ASCII")
print(flag)